// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Ekati.Core
{

public enum DataBlock : byte
{
  NONE = 0,
  NodeID = 1,
  TypeBytes = 2,
  Map = 3,
  Array = 4,
  Primitive = 5,
};


}
