// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Ekati.Core
{

public enum PrimitiveType : sbyte
{
  boolean = 0,
  str = 1,
  i8 = 2,
  i16 = 3,
  i32 = 4,
  i64 = 5,
  ui8 = 6,
  ui16 = 7,
  ui32 = 8,
  ui64 = 9,
  f = 10,
  f32 = 11,
  f64 = 12,
};


}
